---

- name: install git
  package:
    name: git
    state: present

- name: DOTFILES | Checkout latest dotfiles repository
  git:
    repo: "{{ dotfiles_remote }}"
    dest: "{{ dotfiles_local }}"
    update: true
    force: true
