---

- name: include os-specific defaults
  include_vars:
    dir: vars
    files_matching: "{{ ansible_os_family }}.yml"

- name: check git availability
  shell: command -v git >/dev/null 2>&1
  register: git_exists
  ignore_errors: true
  changed_when: false

- name: install git
  package:
    name: git
    state: present
  when: git_exists is failed

- name: checkout latest dotfiles repository
  git:
    repo: "{{ dotfiles_remote }}"
    dest: "{{ dotfiles_local }}"
    update: true
    force: true

- name: symlink dotfiles
  file:
    state: link
    force: true
    src: "{{ dotfiles_local }}/{{ item.file }}"
    path: "{{ item.link }}"

  with_items: "{{ dotfiles_links }}"
  loop_control:
    label: "{{ item.file }}"
